name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:

  # =========================
  # BACKEND
  # =========================
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint
        run: |
          flake8 app.py

      - name: Test
        run: |
          pytest test_app.py -v

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: chamzajutt8/flask-backend:latest


  # =========================
  # FRONTEND
  # =========================
  frontend:
    runs-on: ubuntu-latest
    needs: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check frontend files
        run: |
          echo "Frontend files:"
          ls -la frontend/

          echo "Dockerfile:"
          ls -l frontend/Dockerfile

          echo "Package:"
          ls -l frontend/package.json

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: chamzajutt8/flask-frontend:latest


  # =========================
  # DEPLOY FRONTEND TO GITHUB PAGES
  # =========================
  deploy-pages:
    runs-on: ubuntu-latest
    needs: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
